version: '3.8'

services:
  chiman-project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chiman-project
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      VITE_API_URL: https://api.example.com
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro