apiVersion v1
kind: ConfigMap

metadata:
  name: chiman-project-config:
  labels:
    app chiman-project

data:
  VITE_API_URL: "https://api.example.com"

  VITE_APP_TITLE: "Chiman Project"
